language: java
jdk: oraclejdk7

env:
  global:
    - ANDROID_HOME=$HOME/android-sdk-linux

branches:
  only:
    - WLANAudit3

before_install:
  - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
  # Android SDK tools needs ia32-libs in order to run on 64 bit systems, but it was not installing on Travis
  # To debug apt-get problems, use: "apt-get -o Debug::pkgProblemResolver=yes install ..." and check for broken packages
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes ia32-libs ia32-libs-multiarch; fi
  - wget -nv http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar xfz android-sdk_r21.0.1-linux.tgz -C ~
  - android --silent update sdk --filter platform-tools,android-16,extra-android-support --no-ui --force

script: ant build-debug
